### ISSUE TITLE
401 Unauthorized doesn't work with 401 page type

### ISSUE THREAD

**Issue by rhymeadam** [fritzmg/contao-file-access#11]
Hi there,

I just upgraded a client to Contao 4.13 and it seems that instead of Contao's 401 page type handling this exception as it used to, now we just get a generic "Oops! An Error Occurred. The server returned a "401 Unauthorized" type of screen. Is this something you've seen after upgrading to 4.13? It could also be something in my configuration somewhere, but it's just odd that this wasn't the case when upgrading up until now, and the upgrade to 4.13 has caused this. Please let me know when you can take a look. Thanks!

![Screen Shot 2022-04-06 at 8 24 48 AM](https://user-images.githubusercontent.com/36767740/161973907-aa5d029f-0abc-4798-bbb7-5fd13ded842a.png)
.

**Comment by fritzmg** [comment]
Hm, do you have the domain configured in the website's root?

**Comment by rhymeadam** [comment]
Yeah, so if you're referring to the root page in Contao i.e. tl_page.dns being set to the correct domain, then yes that's set.

**Comment by fritzmg** [comment]
Should be fixed in version `2.3.1` now.
