### ISSUE TITLE
PDF shows code only

### ISSUE THREAD

**Issue by Misco** [fritzmg/contao-file-access#12]
We wanna protect pdf files, but then they dont show up as normal instead like this:

`%PDF-1.5 %���� 101 0 obj <> endobj 125 0 obj <>/Filter/FlateDecode/ID[<7AE21005B5224647A88BA6DCA8DD2BA8><198D096555EBA04697942A246C9C837D>]/Index[101 36]/Info 100 0 R/Length 115/Prev 3719189/Root 102 0 R/Size 137/Type/XRef/W[1 3 1]>>stream h�bbd```b``�"׃H-��D�����j����`Y0� �g��&��$3���= R|��)��2D6ZIFAg ����U_�.a`$������;@��\X endstream endobj startxref 0 %%EOF 136 0 obj <>stream h�b```���,gD@��(���1�Ai P�"D؁��H1ױ1�]���X ۃ���xg�%,�Xˠ7�a��D!� B� �"wD#�l2�C3�E�Z��"�d��Y�c�J�>[S�>>> endobj 103 0 obj <> endobj 104 0 obj <>/ExtGState<>/Font<>/ProcSet[/PDF/Text/ImageC]/XObject<>>>/Rotate 0/TrimBox[0.0 0.0 595.276 841.89]/Type/Page>> endobj 105 0 obj <>stream`
....

what can i do? thanks

**Comment by fritzmg** [comment]
Which Contao version?

**Comment by Misco** [comment]
4.9.34

**Comment by fritzmg** [comment]
This is actually a bug in Symfony: https://github.com/symfony/symfony/pull/47746

As a workaround you can add the following to your `composer.json`:

```json
"conflict": {
    "symfony/http-foundation": "4.4.46 || 5.4.13 || 6.0.13 || 6.1.5"
}
```

And then run `composer update` again (or `composer update symfony/http-foundation`).

See also https://github.com/contao/conflicts/pull/37

**Comment by Misco** [comment]
thank you, this is working for now.
