### ISSUE TITLE
Contao 4.4 Support

### ISSUE THREAD

**Issue by elcreativo** [fritzmg/contao-file-access#3]
How complex would be an update to Contao 4.4?

**Comment by fritzmg** [comment]
It's doable - however, it will still take some time until the project for which we need this extension is updated to Contao 4. It is scheduled for Q3 or Q4 of this year.

**Comment by elcreativo** [comment]
What would it cost to do the update earlier? Or is there no way to do it before Q3/4?

**Comment by fritzmg** [comment]
There is, we just don't have the time/resources 😁. May be I'll get around to it in ~ April.

**Comment by elcreativo** [comment]
Can you give me an approximate cost estimate? Alternatively, is there a way to temporarily protect the folders until the update is done?

**Comment by fritzmg** [comment]
Please send me an inquiry at my public GitHub email address.

**Comment by elcreativo** [comment]
Hello @fritzmg did you get my message via email?

**Comment by fritzmg** [comment]
Yes, I just replied  - sorry for the late response.

**Comment by fritzmg** [comment]
Contao 4 support released with version `2.x`!
