### ISSUE TITLE
Dateiverwaltung "mehrere bearbeiten" "erlaubte Mitgliedergruppen" anpassen geht nicht

### ISSUE THREAD

**Issue by harm2o** [fritzmg/contao-file-access#8]
Wie im [contao-Forum beschrieben](https://community.contao.org/de/showthread.php?78185-Dateiverwaltung-quot-mehrere-bearbeiten-quot-quot-erlaubte-Mitgliedergruppen-quot-anpassen-geht-nic) 

Wenn ich mit Adminrechten einen Dateiordner mit Unterordnern dupliziere und dann über "mehrere bearbeiten" die "Erlaubte Mitgliedergruppen" anpassen möchte, bekomme ich nur leere Zeilen.

**Comment by fritzmg** [comment]
Possibly related to https://github.com/contao/contao/issues/2577

**Comment by fritzmg** [comment]
Fixed and released in `2.2.1`.
