### ISSUE TITLE
Funktioniert nicht mit .php Dateien

### ISSUE THREAD

**Issue by DenizGelion** [fritzmg/contao-file-access#9]
Hallöchen,

bei einer aktuellen Contao 4.9.13 Installation versuchen wir gerade eine PHP-Datei ausführen zu lassen, aber nur für bestimmte, eingeloggte Mitglieder. Das Ganze funktioniert prima mit dem Insert Tag {{file}}, aber sobald wir euer Plugin installieren und einstellen, kommt bei Aufruf der Seite / PHP-Datei einfach nur "File not found."
Bei den meisten anderen Dateien, mit denen es wir probiert haben, (jpg, gif, png) funktioniert es prima. Ist das so gewollt, bzw. wie bekommen wir das gleiche Ergebnis mit .php Dateien hin?

MfG

**Comment by fritzmg** [comment]
Das ist nicht das Konzept dieser Extension. Mit dieser Extension kann man man den Zugriff auf Dateien steuern, die sich ansonsten in einem nicht öffentlichen Ordner befinden.

PHP Dateien werden jedoch direkt vom Web Server ausgeführt.

Ich denke da müsst ihr euer Konzept nochmal überdenken. Poste zB mal im Community Forum, was ihr genau machen wollt.
